print(" ")#define una linea en blanco
print(" Roman De la Cruz Leonardo Antonio, numero 1211, 3-w")
print(" ")#define una linea en blanco
#solicita que ingresemos la base del rectangulo 
base = float(input("Ingresa la base del rectangulo: "))
print(" ")#define una linea en blanco
#solicita la altura del rectangulo
altura = float(input("Ingresa la altura del rectangulo: "))
print(" ")#define una linea en blanco
#operaciones realizadas
perimetro = 2 * (base + altura)
area = base * altura


print(" ")#define una linea en blanco
print("El perimetro del rectangulo es:", perimetro)#imrpjme valores
print(" ")#define una linea en blanco
print("El area del rectangulo es:", area)#imprime valores
print(" ")#define una linea en blanco