print(" ")
print(" Roman De la Cruz leonardo Antonio, numero 1211, 3-w")
print(" ")#define una linea en blanco
numero = int(input("Ingresa un numero natural: "))
print(" ")#define una linea en blanco

# marca si el numero esta dentro de el limite
if 1 <= numero <= 12:
    print("")#define una linea en blanco
    print("El numero", numero," dentro de los numeros naturales.")
    print(" ")#define una linea en blanco
else:
    print("El numero",numero," no esta dentro de los de numeros naturales.")
    print(" ")#define una linea en blanco