print(" ")#define una linea en blanco
print("Roman De la Cruz Leonardo Antonio, numero 1211, 3-w")
print(" ")#define una linea en blanco
# Solicita el valor
numero = int(input("Ingresa un numero natural: "))
print(" ")#define una linea en blanco

# marcara si es par o impar
if numero % 2 == 0:
    print(" ")#define una linea en blanco
    print("El numero", numero,"es par.")#Print imprime si es par
    print(" ")#define una linea en blanco
else:
    print(" ")#define una linea en blanco
    print("El numero",numero," es impar.")#print imprime si es impar
    print(" ")#define una linea en blanco