print(" ")#define una linea en blanco
print("Roman De la Cruz Leonardo Antonio. numero 1211, 3-w ")
print(" ")#define una linea en blanco
numero = int(input("Ingresa un numero entero: "))
print(" ")#define una linea en blanco
if numero % 7 == 0 and numero > 40:
    print(" ")#define una linea en blanco 
    print("El numero", numero,"es mayor a 40 y se puede dividir entre 7")
    print(" ")#define una linea en blanco  
else:
    print(" ")#define una linea en blanco
    print("El numero", numero," no se puede dividir")
    print(" ")#define una linea en blanco
     